"use client";

/**
 * Which match the app is looking at.
 *
 * Whistle deploys a new venue per fixture — `MMVault.pot` is immutable and
 * `WhistleHook.setVault` is one-shot — so "switch fixture" means switching a set
 * of addresses, not just an id. Each entry below is a complete deployment; the
 * shared contracts (AgentRegistry, the ENS root registry, USDC, the factory and
 * the oracle) happen to be identical across them, and the per-fixture ones are
 * not.
 *
 * The selection lives in the URL (`?f=<id>`) so a link carries it, and falls back
 * to the newest unsettled fixture — during a demo that is the one being played.
 */

import { createContext, createElement, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
import type { Address } from "viem";

// Generated by `scripts/vendor.mjs` from everything in `deployments/`, newest
// first — see the note there on why this is not a hand-written list.
import allFixtures from "../vendor/fixtures.json";

export interface FixtureDeployment {
  chainId: number;
  fixtureId: string;
  label: string;
  settled: boolean;
  /**
   * The block this fixture's SettlementPot was deployed in.
   *
   * History scans start here. Any other starting point turns "nothing found"
   * into an ambiguous answer.
   */
  deployBlock: number;
  matchOracle: Address;
  settlementPot: Address;
  whistleHook: Address;
  fillRouter: Address;
  mmVault: Address;
  agentRegistry: Address;
  fixtureFactory: Address;
  usdc: Address;
  rootRegistry?: Address;
  /**
   * The spend cap, in whole USDC, the seed gave this fixture's pre-created
   * mandates. The New agent form defaults to it and Resume falls back to it.
   * Absent on fixtures seeded before caps were sized for the stage (2,000,000).
   */
  agentCapUSDC?: string;
}

/** Newest first. The default is the first entry that has not settled. */
export const FIXTURES = allFixtures as unknown as FixtureDeployment[];

export const DEFAULT_FIXTURE = FIXTURES.find((f) => !f.settled) ?? FIXTURES[0]!;

export function fixtureById(id: string | null): FixtureDeployment {
  return FIXTURES.find((f) => f.fixtureId === id) ?? DEFAULT_FIXTURE;
}

interface FixtureContext {
  deployment: FixtureDeployment;
  fixtureId: bigint;
  select: (id: string) => void;
  all: FixtureDeployment[];
}

const Ctx = createContext<FixtureContext | null>(null);

/**
 * One selection, shared.
 *
 * This has to be a context rather than per-component state. With a plain hook,
 * every caller keeps its own copy and reads `?f=` on its own mount — so the
 * header could show one fixture while `useWhistle` was still reading the other,
 * and the page rendered a settled match labelled "not settled".
 *
 * `?f=` is read in an effect rather than during render because the pages are
 * statically prerendered: the server has no query string, and reading it during
 * the first render would not match what the client produces.
 */
export function FixtureProvider({ children }: { children: ReactNode }) {
  const [id, setId] = useState<string>(DEFAULT_FIXTURE.fixtureId);

  useEffect(() => {
    const fromUrl = new URLSearchParams(window.location.search).get("f");
    if (fromUrl && FIXTURES.some((f) => f.fixtureId === fromUrl)) setId(fromUrl);
  }, []);

  const select = useCallback((next: string) => {
    setId(next);
    const url = new URL(window.location.href);
    url.searchParams.set("f", next);
    window.history.replaceState(null, "", url);
  }, []);

  const value = useMemo<FixtureContext>(() => {
    const deployment = fixtureById(id);
    return { deployment, fixtureId: BigInt(deployment.fixtureId), select, all: FIXTURES };
  }, [id, select]);

  return createElement(Ctx.Provider, { value }, children);
}

export function useFixture(): FixtureContext {
  const ctx = useContext(Ctx);
  if (!ctx) throw new Error("useFixture must be used inside <FixtureProvider>");
  return ctx;
}
