"use client";

/**
 * Which match the app is looking at.
 *
 * Whistle deploys a new venue per fixture — `MMVault.pot` is immutable and
 * `WhistleHook.setVault` is one-shot — so "switch fixture" means switching a set
 * of addresses, not just an id. Each entry below is a complete deployment; the
 * shared contracts (AgentRegistry, the ENS root registry, USDC, the factory and
 * the oracle) happen to be identical across them, and the per-fixture ones are
 * not.
 *
 * The selection lives in the URL (`?f=<id>`) so a link carries it, and falls back
 * to the newest unsettled fixture — during a demo that is the one being played.
 */

import { createContext, createElement, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
import { usePathname } from "next/navigation";
import type { Address } from "viem";

// Generated by `scripts/vendor.mjs` from everything in `deployments/`, newest
// first — see the note there on why this is not a hand-written list.
import allFixtures from "../vendor/fixtures.json";

export interface FixtureDeployment {
  chainId: number;
  fixtureId: string;
  label: string;
  settled: boolean;
  /**
   * The block this fixture's SettlementPot was deployed in.
   *
   * History scans start here. Any other starting point turns "nothing found"
   * into an ambiguous answer.
   */
  deployBlock: number;
  matchOracle: Address;
  settlementPot: Address;
  whistleHook: Address;
  fillRouter: Address;
  mmVault: Address;
  agentRegistry: Address;
  fixtureFactory: Address;
  usdc: Address;
  rootRegistry?: Address;
  /**
   * The spend cap, in whole USDC, the seed gave this fixture's pre-created
   * mandates. The New agent form defaults to it and Resume falls back to it.
   * Absent on fixtures seeded before caps were sized for the stage (2,000,000).
   */
  agentCapUSDC?: string;
  /** Presentation order in the fixture list; lower first. */
  order?: number;
  /** Deployed but kept out of the fixture list. */
  hidden?: boolean;
}

/**
 * Every deployed fixture, hidden ones included: what a direct URL, a profile's
 * fixture label or an agent's row resolves against. `vendor.mjs` has already
 * dropped any whose pot has no code on the target chain.
 */
export const ALL_FIXTURES = allFixtures as unknown as FixtureDeployment[];

/** The fixtures the app lists, in presentation order: everything not `hidden`. */
export const FIXTURES = ALL_FIXTURES.filter((f) => !f.hidden);

export const DEFAULT_FIXTURE = FIXTURES.find((f) => !f.settled) ?? FIXTURES[0]!;

export function fixtureById(id: string | null): FixtureDeployment {
  return ALL_FIXTURES.find((f) => f.fixtureId === id) ?? DEFAULT_FIXTURE;
}

interface FixtureContext {
  deployment: FixtureDeployment;
  fixtureId: bigint;
  select: (id: string) => void;
  all: FixtureDeployment[];
}

const Ctx = createContext<FixtureContext | null>(null);

/**
 * One selection, shared.
 *
 * This has to be a context rather than per-component state. With a plain hook,
 * every caller keeps its own copy and reads `?f=` on its own mount — so the
 * header could show one fixture while `useWhistle` was still reading the other,
 * and the page rendered a settled match labelled "not settled".
 *
 * `?f=` is read in an effect rather than during render because the pages are
 * statically prerendered: the server has no query string, and reading it during
 * the first render would not match what the client produces.
 */
const LAST_KEY = "whistle:last-fixture";

export function FixtureProvider({ children }: { children: ReactNode }) {
  const [id, setId] = useState<string>(DEFAULT_FIXTURE.fixtureId);
  const pathname = usePathname();

  /*
   * Which fixture, in order of authority: the path (`/fixtures/<id>` is the
   * fixture screen), then `?f=`, then the last fixture opened in this tab — so
   * My agents and a profile keep reading the match you came from — then the
   * default. The path is read from the router, so a client-side navigation
   * between fixtures switches the contracts every hook reads.
   */
  const fromPath = /^\/fixtures\/(\d+)/.exec(pathname ?? "")?.[1];
  useEffect(() => {
    let next: string | null = null;
    if (fromPath && ALL_FIXTURES.some((f) => f.fixtureId === fromPath)) next = fromPath;
    if (!next) {
      const q = new URLSearchParams(window.location.search).get("f");
      if (q && FIXTURES.some((f) => f.fixtureId === q)) next = q;
    }
    if (!next) {
      try {
        const last = sessionStorage.getItem(LAST_KEY);
        if (last && FIXTURES.some((f) => f.fixtureId === last)) next = last;
      } catch {
        /* private window */
      }
    }
    if (next) setId(next);
    if (fromPath) {
      try {
        sessionStorage.setItem(LAST_KEY, fromPath);
      } catch {
        /* private window */
      }
    }
  }, [fromPath]);

  const select = useCallback((next: string) => {
    setId(next);
    try {
      sessionStorage.setItem(LAST_KEY, next);
    } catch {
      /* private window */
    }
  }, []);

  // The path wins synchronously, so a fixture screen never renders a frame of the default fixture.
  const effective = fromPath && ALL_FIXTURES.some((f) => f.fixtureId === fromPath) ? fromPath : id;
  const value = useMemo<FixtureContext>(() => {
    const deployment = fixtureById(effective);
    return { deployment, fixtureId: BigInt(deployment.fixtureId), select, all: FIXTURES };
  }, [effective, select]);

  return createElement(Ctx.Provider, { value }, children);
}

export function useFixture(): FixtureContext {
  const ctx = useContext(Ctx);
  if (!ctx) throw new Error("useFixture must be used inside <FixtureProvider>");
  return ctx;
}
