[profile.default]
bytecode_hash = "none"
optimizer = true
optimizer_runs = 200
evm_version = "cancun"
ffi = true
fs_permissions = [
    {access = "read-write", path = ".forge-snapshots/"},
    {access = "read", path = "../fixtures/"},
    {access = "read-write", path = "../deployments/"},
]
libs = ["lib"]
out = "out"
solc_version = "0.8.30"
src = "src"
via_ir = false

[lint]
exclude_lints = ["screaming-snake-case-immutable", "screaming-snake-case-const"]
lint_on_build = false

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
